AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TrustVC Storage (Lambda + HTTP API + S3)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 30
    MemorySize: 512
    Architectures: [x86_64]

Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "trustvc-storage-${Env}"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter30Days
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  StorageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "storage-function-${Env}"
      CodeUri: ./
      Handler: lambda.handler
      Environment:
        Variables:
          TT_AWS_BUCKET_NAME: !Ref StorageBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StorageBucket
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: Invoke URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
