AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TrustVC Storage (Lambda + REST API + S3)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 30
    MemorySize: 512
    Architectures: [x86_64]

Resources:
  StorageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "trustvc-storage-function-${Env}"
      CodeUri: ./
      Handler: index.handler
      Environment:
        Variables:
          TT_AWS_BUCKET_NAME: !Sub "trustvc-storage-${Env}"
          API_KEY: !Sub "{{resolve:ssm:/trustvc/${Env}/api-key}}"
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub "trustvc-storage-${Env}"
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        External:
          - core-js
          - ky-universal
          - ky
          - web-streams-polyfill
          - "@trustvc/trustvc"
          - security-context
        EntryPoints:
          - src/functions/storage/index.ts

Outputs:
  ApiUrl:
    Description: Invoke URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
